### ISSUE TITLE
[BUG] cleaning registries for queue for 10 hours

### ISSUE THREAD

**Issue by Raul824** [NeptuneHub/AudioMuse-AI#74]
**Describe the bug**
Cleaning registries is  running from 10+ hours and the Anlysis progress is stuck at 48%.
Have tried restarting it but again it started cleaning registries.

It was stuck before as well once so I restarted it and progress moved from 28% to 29% and continued.
But now it is clearing registries from 10+ hours and is stuck at 48% so I restarted it but it again started clearing registries.

I don't know is it default behavior or a bug as running it for the first time, the mistake I did was I ran it for whole library which I know is huge but don't know whether cancel will cause next analysis again this much time so I am okay to wait as it has already ran for 2 days.

**Environment (please complete the following information):**
 - OS: Pop-OS
 - Deployment: Docker Compose
 - AudioMuse-AI Version: v0.6.6-beta
 - Jellyfin/Navidrome Version: Navidrome 0.58.0
 - Browser: Firefox
 - CPU: Amd Ryzen 3600
 - RAM: 64 GB DDR4
 - Disk: SSD Nvme

**Comment by NeptuneHub** [comment]
Hi, 
Thanks for reaching me but from this log I’m not understanding what is happening.

- the cleaning registry message is when the worker is in idle and don’t have nothing to do;
- then you restarted and for a moment you have error in connection to redis, probably is just because it wasn’t fully restarted;
- the. You re-restarted and you’re showing me a log that terminate with cleaning registry message again.

So if you start AudioMuse-AI, wait that ALL the container go up (Flask, Worker, PostgreSQL and Redis) and click start, if everything work you should look after a couple of minute the name of the album and then the name of the single disk with the probability to be some music genre in the log. When you look this means that the process is working and you just have to leave it do it works.

Then I don’t know how much album/song you have to analyze. If you have 100.000 songs, with only the node describe above, it could takes several days. Of course several days in which you look in the log the name of the songs analyzed. Not the idle message.

If there is some problem that stuck the process, I need to look the error message.

If for example the error message is Redis that crash, and so the connection error to it is not because you restarted but just Redis that crash, this could be the problem. But again looking the log in this way I can say why redis is crashed if this is the case.

So my suggestion is to retry and looking carefully to the log when it start if it really analyzing the song or not, if not and some error appear, just share it here.

Also remember that the analysis doesn’t start from 0 everytime, it keep the state: 
- AudioMuse-AI read everytime the full list of last album (if you’re analyzing all) that is pretty fast, and it star the analysis only on the one not analyzed yet. The one analyzed are stored in the database.

Just for you to know, for 63.000 songs, it take more than 48hours to me that I have 4 server in cluster (mainly i5-6500 4core). 

To another user with a single node with Ryzen 5600g it takes 17.40 hours for 14.000 songs.

So it is something that can takes times the first time that you need to analyze the entire library. Then you analyze just the new one and become faster.

**Comment by Raul824** [comment]
am also confused as it is stuck on 48%
every time I restart it starts cleaning registries. All containers are healthy, I don't know what to do now any suggestions?


<img width="928" height="650" alt="Image" src="https://github.com/user-attachments/assets/592cd513-ca75-45c4-a8cc-0e7dde741020" />

**Comment by NeptuneHub** [comment]
Ok now from the browser point of view, it is running.

What did you see in the worker log? can you get the full log of the worker and past here?
It remains at 48% with 0/100 completed for how much time?

Because I agree you have a big library (10386 album, In my case I have tested till 5000-6000 album) so it should takes days, but not get stucked.

(If you look skipped 5270/10386 exactly means that half of the library is already analyzed and it skip the already analized)

**Comment by Raul824** [comment]
Attached is the log file.
[ai_worker_log.log.gz](https://github.com/user-attachments/files/22451395/ai_worker_log.log.gz)

it is stuck at 48 with 0/100 from 72 hours.

<img width="1080" height="747" alt="Image" src="https://github.com/user-attachments/assets/dfc67d0d-2e8a-4a43-b661-8ffe24f6a1d8" />

**Comment by NeptuneHub** [comment]
The most critical problem looks like a **database connection timeout**. If AudioMuse-AI loses its DB connection, it crashes. I increased the timeout in the code to reduce false “DB unreachable” errors caused by minor overhead. If you’re running via Docker Compose, it might also be worth checking if the container is running out of CPU/RAM (in Kubernetes, this is easier to track, but I haven’t verified it for Docker).

I also fixed some smaller issues related to **Voyager index creation** and **analysis handling**, which should help produce cleaner logs.

👉 In \~20 minutes, the updated fixes will be available in the `:devel` image. Please pull it, re-run the analysis, and share the new logs if errors persist. The process should resume from the last checkpoint.

Additional suggestions:

* If everything works locally, try running **only 1 worker** (your logs suggest you’re running 2 workers, which might contribute to the issue).
* Do you have **very long single-track files** (e.g., a full concert/CD in a 1h+ file)? These don’t make sense for AudioMuse-AI and can create resource problems since the algorithms are designed for song-length tracks. If that’s the case, it might be part of the problem.

If you coud run new test and share new logs in case of issue it will be helpful.

Thanks.

**Comment by Raul824** [comment]
am running it through docker compose but I can't see any restart as all audiomuse containers are up from 35 hours since I last restarted.
I checked htop for cpu and ram consumption after restart but it was mostly free.

Additional suggestions:
Its only running with one worker with Nvidia gpu.
Yes there can be a 1h+ file but analysis isn't even starting or else I would have checked the file in log and have moved it.


Just let me know where to put devel in these images

    image: redis:7-alpine
    image: postgres:15-alpine
    image: ghcr.io/neptunehub/audiomuse-ai:latest-nvidia
    image: ghcr.io/neptunehub/audiomuse-ai:latest-nvidia

**Comment by NeptuneHub** [comment]
Instead of this two:
image: ghcr.io/neptunehub/audiomuse-ai:latest-nvidia
image: ghcr.io/neptunehub/audiomuse-ai:latest-nvidia

you need to put:
image: ghcr.io/neptunehub/audiomuse-ai:devel
image: ghcr.io/neptunehub/audiomuse-ai:devel

You will not have the nvidia support in devel, but at least we start looking if it work. Also the invidia support itself is very experimental because I don't have a GPU to test it myself, so al the test are the one made from the user (yes, at some point I'll need to dedicate more time for some kind of integrated test where applicable).

**Comment by Raul824** [comment]
Well no changes the logs still shows the same thing and progress stuck at 48%.

<img width="1649" height="89" alt="Image" src="https://github.com/user-attachments/assets/3515cbbd-9954-4461-a95f-2a3e837af1bc" />


```
docker logs audiomuse-ai-worker-instance

Starting worker processes via supervisord...
2025-09-23 01:14:31,929 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2025-09-23 01:14:31,933 INFO supervisord started with pid 7
2025-09-23 01:14:32,939 INFO spawned: 'rq-janitor' with pid 8
2025-09-23 01:14:32,941 INFO spawned: 'rq-worker-default' with pid 9
2025-09-23 01:14:32,943 INFO spawned: 'rq-worker-high' with pid 10
[INFO]-[23-09-2025 01-14-33]-Starting AudioMuse-AI Backend version v0.6.8-beta
[INFO]-[23-09-2025 01-14-33]-Starting AudioMuse-AI Backend version v0.6.8-beta
[INFO]-[23-09-2025 01-14-33]-Starting AudioMuse-AI Backend version v0.6.8-beta
[INFO]-[23-09-2025 01-14-33]-Database tables checked/created successfully.
[INFO]-[23-09-2025 01-14-33]-Database tables checked/created successfully.
[INFO]-[23-09-2025 01-14-33]-Database tables checked/created successfully.
2025-09-23 01:14:33.723124: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.723124: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.729806: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.759096: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-09-23 01:14:33.759130: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-09-23 01:14:33.759096: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-09-23 01:14:33.759130: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-09-23 01:14:33.760105: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-09-23 01:14:33.760106: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-09-23 01:14:33.765843: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.765843: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.766015: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-23 01:14:33.766015: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-23 01:14:33.766391: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-09-23 01:14:33.766421: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-09-23 01:14:33.767479: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-09-23 01:14:33.773117: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-09-23 01:14:33.773272: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-23 01:14:34.432035: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2025-09-23 01:14:34,432 INFO success: rq-janitor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-09-23 01:14:34,432 INFO success: rq-worker-default entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-09-23 01:14:34,432 INFO success: rq-worker-high entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-09-23 01:14:34.432856: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2025-09-23 01:14:34.432860: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[WARNING]-[23-09-2025 01-14-34]-From /usr/local/lib/python3.10/dist-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[WARNING]-[23-09-2025 01-14-34]-From /usr/local/lib/python3.10/dist-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[WARNING]-[23-09-2025 01-14-34]-From /usr/local/lib/python3.10/dist-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[WARNING]-[23-09-2025 01-14-34]-From /usr/local/lib/python3.10/dist-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[WARNING]-[23-09-2025 01-14-34]-From /usr/local/lib/python3.10/dist-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
🚀 DEDICATED HIGH PRIORITY RQ Worker starting. Version: v0.6.8-beta. Listening ONLY on queues: ['high']
Using Redis connection: {'socket_connect_timeout': 15, 'socket_timeout': 15, 'host': 'redis', 'port': 6379, 'db': 0}
DEFAULT RQ Worker starting. Version: v0.6.8-beta. Listening on queues: ['default']
Using Redis connection: {'socket_connect_timeout': 15, 'socket_timeout': 15, 'host': 'redis', 'port': 6379, 'db': 0}
[INFO]-[23-09-2025 01-14-35]-🧹 RQ Janitor process starting. Cleaning registries every 10 seconds.
RQ Worker logging level set to: INFO
RQ Worker logging level set to: INFO
[INFO]-[23-09-2025 01-14-35]-Worker b4e349d9e18d4a5eb4700638aea13641: started with PID 10, version 2.6.0
[INFO]-[23-09-2025 01-14-35]-Worker b4e349d9e18d4a5eb4700638aea13641: subscribing to channel rq:pubsub:b4e349d9e18d4a5eb4700638aea13641
[INFO]-[23-09-2025 01-14-35]-Worker 33f30961cd7e44289d0ab3d74f93b411: started with PID 9, version 2.6.0
[INFO]-[23-09-2025 01-14-35]-Worker 33f30961cd7e44289d0ab3d74f93b411: subscribing to channel rq:pubsub:33f30961cd7e44289d0ab3d74f93b411
[INFO]-[23-09-2025 01-14-35]-*** Listening on default...
[INFO]-[23-09-2025 01-14-35]-*** Listening on high...
[INFO]-[23-09-2025 01-14-35]-Worker 33f30961cd7e44289d0ab3d74f93b411: cleaning registries for queue: default
[INFO]-[23-09-2025 01-14-35]-Worker b4e349d9e18d4a5eb4700638aea13641: cleaning registries for queue: high
[INFO]-[23-09-2025 01-24-35]-Worker 33f30961cd7e44289d0ab3d74f93b411: cleaning registries for queue: default
[INFO]-[23-09-2025 01-24-35]-Worker b4e349d9e18d4a5eb4700638aea13641: cleaning registries for queue: high
```

P.S 

I took the backup of postgres data and restarted it from scratch.
Did the analysis for 2 albums and it worked without any issues so I am wondering may be some queue or database issue?


<img width="994" height="589" alt="Image" src="https://github.com/user-attachments/assets/43d05cf7-8ada-4f2c-a779-151015246573" />


Then I copied the backup and started  this time I cancelled the current task and started analysis again now it's progressing as It has now reached 49% and is skipping the ones which are already progressed but I can see nvidia gpu being used and logs showing the scans.
Will keep you posted if it gets stuck again.


<img width="968" height="687" alt="Image" src="https://github.com/user-attachments/assets/ea7cddab-37a4-42bd-b245-f4c075764534" />

**Comment by Raul824** [comment]
<img width="1080" height="639" alt="Image" src="https://github.com/user-attachments/assets/a2bb1aaf-c154-452a-8ca1-05e50885409d" />

It got completed.
solution was to cancel and start again.
